# Dockerfile for Producer 
FROM python:3

# install pika to access rabbitmq
RUN pip3 install flask
RUN pip3 install pika
RUN pip3 install requests

# Without this setting, Python never prints anything out.
ENV PYTHONUNBUFFERED=1

# declare the source directory
WORKDIR /home/chakita/cclab/CloudHack_2/app/producer

# copy the file
COPY producer.py .

# start command
CMD [ "python3", "producer.py" ]
