version: "2.1"
services:
  rabbitMQ_server:
    image: rabbitmq:3.8-rc-management
    container_name: rmq 
    ports:
       - "5672:5672"
    #restart:
  producer:
    build:
      context: .
      dockerfile: ./Dockerfile_producer
    ports:
       - "5200:5200"
    depends_on:
      - rabbitMQ_server
    environment:
      AMQP_URL: 'amqp://rmq?connection_attempts=5&retry_delay=10'
      
  ride_matching1:
    build: 
       context: . 
       dockerfile: ./Dockerfile_ride_matching
    environment:
      AMQP_URL: 'amqp://rmq?connection_attempts=5&retry_delay=10'
      CONSUMER_ID: 1
      SERVER_IP: 'producer:5200'
    depends_on:
       - rabbitMQ_server
       - producer
  ride_matching2:
    build: 
       context: . 
       dockerfile: ./Dockerfile_ride_matching
    environment:
      AMQP_URL: 'amqp://rmq?connection_attempts=10&retry_delay=10'
      CONSUMER_ID: 2
      SERVER_IP: 'producer:5200'
    depends_on:
       - rabbitMQ_server
       - producer
      
  ride_database:
    build: 
      context: .
      dockerfile: ./Dockerfile_db
    environment:
       AMQP_URL: 'amqp://rmq?connection_attempts=10&retry_delay=10'
    depends_on:
      - rabbitMQ_server
      - producer
      
